### ISSUE TITLE
插件在 9.9.10-23873 (64位) 中无法使用...具体看图

### ISSUE THREAD

**Issue by QQ804218** [yuyumoko/LiteLoaderQQNT-Plugin-Eencode#8]
![微信截图_20240519093730](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/67571282/0b0b3084-bff1-4645-b84a-3c8267504e65)

**Comment by shuangshun** [comment]
插件功能可以使用,但无法切换分群加密; 加密发送按钮显示错误,但不影响使用

**Comment by blblkang** [comment]
按钮显示错误？我这里直接没有这个按钮了

**Comment by yuyumoko** [comment]
修了一下 , 可以在插件内更新看看

**Comment by MisakaSophia** [comment]
> 修了一下 , 可以在插件内更新看看

![QQ截图20240603092809](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/125279361/e8b8d80d-c18b-4eb8-8ac5-fc1ce4f1db74)
还是没按钮

**Comment by shuangshun** [comment]
直接git拉源码替换掉旧的,替换掉后我这一切正常

**Comment by xiaole3349** [comment]
> 直接git拉源码替换掉旧的,替换掉后我这一切正常

好的，我试试

**Comment by ililaoban** [comment]
> 修了一下 , 可以在插件内更新看看

还是没有按钮

​ Uncaught ReferenceError: LLAPI is not defined
    at local:\plugins\LiteLoaderQQNT-Plugin-Eencode\injects\renderer.js:231:9

**Comment by yuyumoko** [comment]
> > 修了一下 , 可以在插件内更新看看
> 
> 还是没有按钮
> 
> ​ Uncaught ReferenceError: LLAPI is not defined at local:\plugins\LiteLoaderQQNT-Plugin-Eencode\injects\renderer.js:231:9

你需要安装 `LLAPI` 这个插件

**Comment by xiaole3349** [comment]
> > > 修了一下 , 可以在插件内更新看看
> > 
> > 
> > 还是没有按钮
> > ​ Uncaught ReferenceError: LLAPI is not defined at local:\plugins\LiteLoaderQQNT-Plugin-Eencode\injects\renderer.js:231:9
> 
> 你需要安装 `LLAPI` 这个插件

原来如此，建议在README中写上需要前置插件 LLAPI。

**Comment by ililaoban** [comment]
更新十分钟前的最新版😭后,liteloader直接没了

**Comment by ililaoban** [comment]
> > 更新十分钟前的最新版![😭](https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f62d.svg)后,liteloader直接没了
> 
> 要不试试下载一下源码吧, 可能更新有问题

能用了，谢谢！

**Comment by MisakaSophia** [comment]
新版qq貌似专门屏蔽这个，这个插件放到plugins文件夹，所有插件都加载不了，单独把这个插件去掉又能加载其他插件
![QQ_1720590354889](https://github.com/yuyumoko/LiteLoaderQQNT-Plugin-Eencode/assets/125279361/eb33d8c0-4e2c-48f6-8345-39b3641e50ec)

**Comment by yuyumoko** [comment]
> 新版qq貌似专门屏蔽这个，这个插件放到plugins文件夹，所有插件都加载不了，单独把这个插件去掉又能加载其他插件 ![QQ_1720590354889](https://private-user-images.githubusercontent.com/125279361/347272481-eb33d8c0-4e2c-48f6-8345-39b3641e50ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTIzNjQsIm5iZiI6MTcyMDYxMjA2NCwicGF0aCI6Ii8xMjUyNzkzNjEvMzQ3MjcyNDgxLWViMzNkOGMwLTRlMmMtNDhmNi04MzQ1LTM5YjM2NDFlNTBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMTQ3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjVkMzEwZDI5ZTE5OGZjZWFiMjg4ZGZmY2Q2Y2FjNDQ3OTcyZDgyNWVjYzdjY2YyODFmMjc1NWM3ZGY2MGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aj3Bsqhig9rFx-9NLrS_MJm6PnetZaYNSQxZee8wwyA)

我换了个库, 重新安装试试

**Comment by MisakaSophia** [comment]
> > 新版qq貌似专门屏蔽这个，这个插件放到plugins文件夹，所有插件都加载不了，单独把这个插件去掉又能加载其他插件 ![QQ_1720590354889](https://private-user-images.githubusercontent.com/125279361/347272481-eb33d8c0-4e2c-48f6-8345-39b3641e50ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTIzNjQsIm5iZiI6MTcyMDYxMjA2NCwicGF0aCI6Ii8xMjUyNzkzNjEvMzQ3MjcyNDgxLWViMzNkOGMwLTRlMmMtNDhmNi04MzQ1LTM5YjM2NDFlNTBlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMTQ3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjVkMzEwZDI5ZTE5OGZjZWFiMjg4ZGZmY2Q2Y2FjNDQ3OTcyZDgyNWVjYzdjY2YyODFmMjc1NWM3ZGY2MGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aj3Bsqhig9rFx-9NLrS_MJm6PnetZaYNSQxZee8wwyA)
> 
> 我换了个库, 重新安装试试

非常感谢，能用了

**Comment by blblkang** [comment]
现在是内置LLAPI了吗

**Comment by blblkang** [comment]
> 现在是内置LLAPI了吗

好吧，我没有看，所以是内置了Euphony吗
